version: "3.5"
services:
  etherpad:
    container_name: dv_etherpad
    build: .
    environment:
      DB_HOST: ${POSTGRES_HOST}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_PORT: ${POSTGRES_PORT}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - 3000:9001
    depends_on:
      - db
