version: "3.5"
services:
  db:
    container_name: dv_postgres
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /data/postgres
    ports:
      - 5432:5432
  etherpad:
    container_name: dv_etherpad
    build: .
    environment:
      DB_HOST: db
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_PORT: ${POSTGRES_PORT}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - 3000:9001
    depends_on:
      - db
